// Typology ids
export const ROLES = {
  ADMIN: process.env.REACT_APP_ROLE_ADMIN,
  LECTURE_REVIEWER: process.env.REACT_APP_ROLE_LECTURE_REVIEWER,
  LECTURE: process.env.REACT_APP_ROLE_LECTURE,
  STUDENT: process.env.REACT_APP_ROLE_STUDENT,
  LECTURER_NOT_VERIFIED: process.env.REACT_APP_ROLE_LECTURER_NOT_VERIFIED,
};
